Crowdfunding raise
xtrades-net/xtrades-homepages pull request #165
Opened 2024-01-23 11:54 UTC by yuliaMasliak

2024-01-23 14:20 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/app/core/testimonials.service.ts
> +export interface TestimonialModel {
let's create a model folder and move it there

2024-01-23 14:28 UTC, ArtyomYatskevich requested changes

2024-01-23 14:28 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/app/core/testimonials.service.ts
> +import {LoadingService} from "@core/loading.service";
it is not used, please remove it

2024-01-23 14:28 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/app/layouts/promo-layout/promo-layout.component.ts
> +  ngOnInit(): void {}
do you really need this empty method ?

2024-01-23 14:28 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/app/shared/components/text-slider/text-slider.component.ts
> +  @Input() type = '';
It would be great to create 'enum' for this

2024-01-23 15:49 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/app/shared/components/text-slider/text-slider.component.html
> +        <div class="slide column slider-container" *ngIf="type !== 'promo'">
please use enum here instead of this string

2024-01-23 15:56 UTC, yuliaMasliak commented on Xtrades.XtradesMarketingPage/src/app/shared/components/text-slider/text-slider.component.html
> +        <div class="slide column slider-container" *ngIf="type !== 'promo'">
Should I create a new variable for it in the controller?
like:
public currentSliderType = sliderType;  (our imported enum)

and then in the template use it as:
 *ngIf="type !== currentSliderType.promo"

2024-01-23 15:58 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/app/shared/components/text-slider/text-slider.component.html
> +        <div class="slide column slider-container" *ngIf="type !== 'promo'">
@yuliaMasliak  yep, in the component

2024-01-24 08:18 UTC, ArtyomYatskevich approved these changes
lgtm

2024-01-24 08:20 UTC, merged