App structure update
xtrades-net/xtrades-homepages pull request #178
Opened 2024-02-14 10:24 UTC by yuliaMasliak

The main change that needs to be reviewed is that the main layout module was removed from the app's routing and structure. I have analyzed its usage and as far as I see it was unnecessary and redundant. 
The purpose of these changes is to make the app structure cleaner.

2024-02-19 11:34 UTC, ArtyomYatskevich commented
@yuliaMasliak  Could you please try to reach @kurtiev to ask him why he introduced these layers before in this commit
https://github.com/xtrades-net/xtrades-homepages/commit/19b0d7d1615a00b7bf875b165befe8a0fc40ceea#diff-5c956ca006864b4eb0eab882ed40d36fda79dc086175db7d391f4edc17de5adc
because you are actually just reverting his changes

2024-02-19 11:34 UTC, ArtyomYatskevich requested changes

2024-02-19 11:34 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/app/shared/components/footer-new/footer.component.html
> +      <span>© Copyright 2022 - Xtrades. All rights reserved.</span>
Why did you decide to change it to 2022?

2024-02-19 11:34 UTC, ArtyomYatskevich commented on Xtrades.XtradesMarketingPage/src/styles.scss
>    &::placeholder {
If you are sure that it is not needed then please remove this css selector and below as well

2024-02-21 08:44 UTC, yuliaMasliak commented on Xtrades.XtradesMarketingPage/src/app/shared/components/footer-new/footer.component.html
> +      <span>© Copyright 2022 - Xtrades. All rights reserved.</span>
Hm... very strange, do not remember that I made this change, maybe smth overrides the content. Will update it to  2024

2024-02-21 10:12 UTC, yuliaMasliak commented
I have asked Fikret about his changes, he replied he had added a separate main layout module because he could not implement new designs for some pages. 
![image](https://github.com/xtrades-net/xtrades-homepages/assets/110036110/dc9dba9f-fa47-4ec9-b507-5ee0c540f4fd)

2024-02-21 10:18 UTC, yuliaMasliak commented on Xtrades.XtradesMarketingPage/src/app/shared/components/footer-new/footer.component.html
> +      <span>© Copyright 2022 - Xtrades. All rights reserved.</span>
I remembered, I had changed it to 2022 because we have 2022 year at our main home page footer. Should I update it to 2024 as well?

2024-02-21 10:24 UTC, yuliaMasliak commented on Xtrades.XtradesMarketingPage/src/app/shared/components/footer-new/footer.component.html
> +      <span>© Copyright 2022 - Xtrades. All rights reserved.</span>
Update all to 2024

2024-02-23 08:56 UTC, ArtyomYatskevich approved these changes

2024-02-23 12:16 UTC, merged